### ISSUE TITLE
uses deprecated registry.terraform.io/hashicorp/template v2.2.0

### ISSUE THREAD

**Issue by tedparagon** [cloudposse/terraform-yaml-config#26]
## Describe the Bug
The yaml config module makes use of the template_file data resource instead of the templatefile function. Since there is no registry.terraform.io/hashicorp/template v2.2.0 provider for Apple M1 systems any attempts to use this module will fail.

```
Initializing provider plugins...
- Finding latest version of hashicorp/template...
╷
│ Error: Incompatible provider version
│
│ Provider registry.terraform.io/hashicorp/template v2.2.0 does not have a package available for your current platform, darwin_arm64.
│
│ Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms. Other versions of this provider may have different platforms supported.
╵
```

## Expected Behavior
Module initializes without the need for the deprecated registry.terraform.io/hashicorp/template provider.

## Steps to Reproduce
1. Perform `terraform init` on a MacBook with a M1 chip (darwin_arm64)
2. Error above will be displayed.

## Environment (please complete the following information):

Anything that will help us triage the bug will help. Here are some ideas:
 - OS: macOS
 - Version: 13
 - Chip: Apple M1 Pro

See https://github.com/hashicorp/terraform/issues/30055

**Comment by osterman** [comment]
This was closed in #25
